version: '3.8'
services:
    php:
        build:
            context: ./php/
            dockerfile: Dockerfile
        expose:
          - 9000
        volumes:
            - ./project:/var/www/html
        networks:
            - backend
        container_name: "${PHP_NAME}"
    web:
        build:
            context: ./apache/
            dockerfile: Dockerfile
            args:
                - "HTTPD_LOG_DIR=${APACHEdo_LOG_DIR}"
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./project:/var/www/html
        networks:
            - backend
        container_name: "${APACHE_NAME}"
networks:
    backend:
    frontend:
volumes:
    myserver:
        external: true

